### ISSUE TITLE
Sequence.py fails to predict any sequences

### ISSUE THREAD

**Issue by lukingtn** [ogmacorp/PyOgmaNeo#2]
I've installed pyogmaneo per the instructions, and to test it ran "python Sequence.py"

1 platforms found.
Using platform: Apple
Using device: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
False
False
False
False
False
False
...
...
False

All the way through the iterations. Is this the expected result? I would have assumed that the Sequence Demo would have been able to predict some sequences over 1500 iterations.

**Comment by lukingtn** [comment]
This seems to only be the case when using _cpu, _gpu appears to work correctly.

**Comment by rcrowder** [comment]
Hi @lukingtn As you've seen the Apple OpenCL `GPU` device works as expected. Apple imposes strict limits with it's OpenCL CPU device (1D maximum work item sizes) that differs from other OS and vendor implementations. With the way the OgmaNeo kernel code works it will be tricky to arrange it to cope with those limits. I'll have a look at adding a check for limited work item sizes, output of a warning from the OgmaNeo library, and a fallback to the GPU device on Apple Mac OS X.

**Comment by rcrowder** [comment]
The latest release of OgmaNeo library now has code to check for work item sizes, and falls back to trying to use a _gpu device if the work item sizes are not compatible - https://github.com/ogmacorp/OgmaNeo/blob/master/source/system/ComputeSystem.cpp#L55-L74
